Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [5]:
#Consider the below code to answer further questions:

import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2.Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in the list
print("Data types of elements in list_:")
for item in list_:
    print(f"{item}: {type(item)}")

# Print data type of each element in the NumPy array
print("\nData types of elements in array_list:")
for item in array_list:
    print(f"{item}: {type(item)}")

Data types of elements in list_:
1: <class 'str'>
2: <class 'str'>
3: <class 'str'>
4: <class 'str'>
5: <class 'str'>

Data types of elements in array_list:
1: <class 'numpy.str_'>
2: <class 'numpy.str_'>
3: <class 'numpy.str_'>
4: <class 'numpy.str_'>
5: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and

arra_list? If so then print the data types of each and every element present in both the variables, list_

and arra_list.

In [7]:
import numpy as np

list_ = [1, 2.5, '3']
try:
    array_list = np.array(object=list_, dtype=int)
except ValueError as e:
    print("Error while creating array_list:", e)

print("Data types in list_:")
for i, item in enumerate(list_):
    print(f"list_[{i}] = {item}, type = {type(item)}")

if 'array_list' in locals():
    print("\nData types in array_list:")
    for i, item in enumerate(array_list):
        print(f"array_list[{i}] = {item}, type = {type(item)}")

Data types in list_:
list_[0] = 1, type = <class 'int'>
list_[1] = 2.5, type = <class 'float'>
list_[2] = 3, type = <class 'str'>

Data types in array_list:
array_list[0] = 1, type = <class 'numpy.int64'>
array_list[1] = 2, type = <class 'numpy.int64'>
array_list[2] = 3, type = <class 'numpy.int64'>


Consider the below code to answer further questions:

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [12]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array.shape)
print(num_array.size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [15]:
import numpy as np
zeroes_matrix=np.zeros([3,3])
print(zeroes_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions

In [18]:
import numpy as np
identity_matrix=np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
